/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root'
import { Route as indexRouteImport } from './routes/index'
import { Route as not_foundRouteImport } from './routes/not_found'
import { Route as playRouteImport } from './routes/play'

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const not_foundRoute = not_foundRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const playRoute = playRouteImport.update({
  id: '/play/$runId',
  path: '/play/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/$': typeof not_foundRoute
  '/play/$runId': typeof playRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/$': typeof not_foundRoute
  '/play/$runId': typeof playRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/$': typeof not_foundRoute
  '/play/$runId': typeof playRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/play/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/play/$runId'
  id: '__root__' | '/' | '/$' | '/play/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  not_foundRoute: typeof not_foundRoute
  playRoute: typeof playRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof not_foundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$runId': {
      id: '/play/$runId'
      path: '/play/$runId'
      fullPath: '/play/$runId'
      preLoaderRoute: typeof playRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  not_foundRoute: not_foundRoute,
  playRoute: playRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
